### ISSUE TITLE
Broken ?

### ISSUE THREAD

**Issue by senare** [emilkarlen/exactly#1]
dev-manfre:~/repos/git/playground/jaxlondon/consumer [master] $ exactly test.case 
Traceback (most recent call last):
  File "/usr/local/bin/exactly", line 7, in <module>
    from exactly_lib.default.default_main_program_setup import main
  File "/usr/local/lib/python2.7/site-packages/exactly_lib/default/default_main_program_setup.py", line 14
    def default_main_program() -> main_program.MainProgram:
                               ^
SyntaxError: invalid syntax

**Comment by emilkarlen** [comment]
Unsupported python version, must use >= 3.4
